import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BarChart,Bar,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,ResponsiveContainer,AreaChart,Area} from 'recharts';
import {BrainCircuit,Play,Target,TrendingUp,ShieldCheck,RefreshCw,AlertCircle,FlaskConical,History,Users,GitCompare,Lightbulb,Bot} from 'lucide-react';import './styles.css';
const money=n=>'₹'+Math.round(n||0).toLocaleString('en-IN');const pct=n=>((n||0)*100).toFixed(1)+'%';
const API_URL = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '');

async function api(u,o={}) {
  let r = await fetch(`${API_URL}${u}`, o);
  if (!r.ok) {
    let m = 'Request failed';
    try {
      let j = await r.json();
      m = j.detail || j.message || m;
    } catch {}
    throw Error(m);
  }
  return r.json();
}
function Card({title,value,sub,icon}){return <div className="card"><div className="icon">{icon}</div><small>{title}</small><strong>{value}</strong><span>{sub}</span></div>}
function App(){const [tab,setTab]=useState('overview'),[summary,setSummary]=useState(null),[result,setResult]=useState(null),[opt,setOpt]=useState(null),[experiments,setExperiments]=useState(null),[history,setHistory]=useState([]),[segments,setSegments]=useState([]),[radar,setRadar]=useState(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const [text,setText]=useState('What if I give new customers 10% discount?');const [s,setS]=useState({name:'10% New Customer Discount',discount_pct:10,price_change_pct:0,cod_share_pct:40,campaign_strength:40,target_new_customers:true,objective:'profit',simulations:250,free_shipping:false,cashback_pct:0,min_order_value:0});
 const load=async()=>{setError('');try{let x=await api('/api/summary');setSummary(x)}catch(e){setError(e.message)}};useEffect(()=>{load();api('/api/segments').then(setSegments).catch(()=>{});api('/api/radar').then(setRadar).catch(()=>{});},[]);
 const interpret=async()=>{try{let x=await api('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});setS(v=>({...v,...x}));}catch(e){setError(e.message)}};
 const simulate=async()=>{setLoading(true);setError('');try{setResult(await api('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)}));}catch(e){setError(e.message)}finally{setLoading(false)}};
 const optimize=async()=>{setBusy(true);try{setOpt(await api('/api/optimize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({objective:s.objective})}))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const runExp=async()=>{setBusy(true);try{setExperiments(await api('/api/experiment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({objective:s.objective})}))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const runAgent=async()=>{setBusy(true);try{let x=await api('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});setResult(v=>v?{...v,agent:x}:null);alert(`Agent tested ${x.strategies_tested} strategies. Best: ${x.best.discount_pct}% discount. Approval required before action.`)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const loadHist=()=>api('/api/history').then(setHistory).catch(e=>setError(e.message));const b=summary?.metrics||{};
 return <div className="app"><aside><div className="brand"><BrainCircuit/><div>Merchant<br/><b>Digital Twin</b></div></div><div className="tag">WHAT-IF DECISION ENGINE</div><nav>{[['overview',TrendingUp,'Overview'],['scenarios',Target,'Scenarios'],['segments',Users,'Segments'],['experiments',FlaskConical,'Experiments'],['history',History,'Audit History']].map(([id,I,label])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);if(id==='history')loadHist()}} key={id}><I/> {label}</button>)}</nav><div className="side-note"><ShieldCheck/><b>Decision before action</b><small>All financial calculations come from the simulation engine. Production actions require merchant approval.</small></div></aside>
 <main><header><div><div className="eyebrow">AI GROWTH & AGENTIC COMMERCE</div><h1>Simulate before you act.</h1><p>Explore alternate futures on a virtual copy of your merchant operation.</p></div><button className="ghost" onClick={load}><RefreshCw size={16}/> Refresh</button></header>{error&&<div className="alert"><AlertCircle size={18}/>{error}</div>}
 {tab==='overview'&&<><section className="cards"><Card title="Revenue" value={summary?money(b.revenue):'—'} sub="Current baseline" icon={<TrendingUp/>}/><Card title="Profit" value={summary?money(b.profit):'—'} sub="Contribution estimate" icon={<Target/>}/><Card title="Orders" value={summary?Math.round(b.orders||0).toLocaleString():'—'} sub="Per 10,000 visits" icon={<TrendingUp/>}/><Card title="RTO" value={summary?pct(b.rto):'—'} sub="Return-to-origin risk" icon={<ShieldCheck/>}/></section><section className="panel hero"><div><span className="pill">Digital Twin Confidence {summary?.confidence||'—'}/100</span><h2>Ask your business</h2><p>Type a business question. The engine parses it, simulates it and explains the outcome.</p></div><textarea value={text} onChange={e=>setText(e.target.value)}/><div className="actions"><button onClick={interpret}><Lightbulb size={16}/> Interpret</button><button className="primary" onClick={simulate} disabled={loading||!summary?.ready}><Play size={16}/>{loading?'Simulating…':'Run simulation'}</button><button className="dark" onClick={runAgent} disabled={busy}><Bot size={16}/> Agent test</button></div><small>Try: “Increase price by 8%”, “Give new customers 15% off”, “5% cashback + free shipping”.</small></section><section className="grid2"><Controls s={s} setS={setS}/><Decision result={result}/></section>{result&&<Results result={result}/>}<section className="grid2"><Optimizer opt={opt} optimize={optimize} busy={busy}/><Risk radar={radar}/></section></>}
 {tab==='scenarios'&&<><section className="grid2"><Controls s={s} setS={setS}/><div className="panel"><h2>Strategy comparison</h2><p>Compare multiple policies in one view.</p>{opt?<table><thead><tr><th>Discount</th><th>Revenue</th><th>Profit</th><th>Orders</th><th>RTO</th></tr></thead><tbody>{opt.scenarios.map(x=><tr key={x.discount_pct}><td>{x.discount_pct}%</td><td>{money(x.revenue)}</td><td>{money(x.profit)}</td><td>{Math.round(x.orders)}</td><td>{pct(x.rto)}</td></tr>)}</tbody></table>:<button onClick={optimize}>Run strategy comparison</button>}</div></section></>}
 {tab==='segments'&&<section className="panel"><h2>Customer Segment Digital Twin</h2><p>Simulate policy changes against distinct customer populations.</p><table><thead><tr><th>Segment</th><th>Customers</th><th>AOV</th><th>Conversion</th><th>RTO</th></tr></thead><tbody>{segments.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.customers.toLocaleString()}</td><td>{money(x.avg_order_value)}</td><td>{pct(x.conversion)}</td><td>{pct(x.rto)}</td></tr>)}</tbody></table></section>}
 {tab==='experiments'&&<section className="panel"><div className="panel-head"><div><h2>AI Experiment Designer</h2><p>Generate bounded strategies for a stated goal.</p></div><button onClick={runExp} disabled={busy}>{busy?'Testing…':'Generate experiments'}</button></div>{experiments?.experiments.map((x,i)=><div className="experiment" key={x.name}><b>{i===0?'🏆 ':''}{x.name}</b><span>{x.scenario.discount_pct}% discount · {x.scenario.target_new_customers?'new customers · ':''}{x.scenario.free_shipping?'free shipping · ':''}{x.scenario.cashback_pct}% cashback</span><strong>{x.delta_profit>=0?'+':''}{money(x.delta_profit)} profit impact</strong></div>)}</section>}
 {tab==='history'&&<section className="panel"><h2>Simulation Receipts & Audit Trail</h2><p>Every simulation is logged with an audit ID.</p><table><thead><tr><th>ID</th><th>Time</th><th>Scenario</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.id}</td><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.scenario}</td></tr>)}</tbody></table></section>}
 <footer>Merchant Digital Twin · Synthetic-data prototype · Advisory only · No production action without approval</footer></main></div>}
function Controls({s,setS}){return <section className="panel"><div className="panel-head"><div><h2>Scenario controls</h2><p>Change variables without touching production.</p></div></div><div className="formgrid">{[['discount_pct','Discount %'],['price_change_pct','Price change %'],['cod_share_pct','COD share %'],['campaign_strength','Campaign strength'],['cashback_pct','Cashback %'],['min_order_value','Min order value']].map(([k,l])=><label key={k}>{l}<input type="number" value={s[k]} onChange={e=>setS({...s,[k]:+e.target.value})}/></label>)}</div><label className="check"><input type="checkbox" checked={s.target_new_customers} onChange={e=>setS({...s,target_new_customers:e.target.checked})}/> Target new customers only</label><label className="check"><input type="checkbox" checked={s.free_shipping} onChange={e=>setS({...s,free_shipping:e.target.checked})}/> Free shipping</label><label>Optimization goal<select value={s.objective} onChange={e=>setS({...s,objective:e.target.value})}><option value="profit">Maximum Profit</option><option value="revenue">Maximum Revenue</option><option value="orders">Maximum Orders</option><option value="conversion">Maximum Conversion</option></select></label></section>}
function Decision({result}){return <section className="panel"><h2>AI decision</h2>{result?<div className={result.recommendation.decision==='RECOMMENDED'?'decision good':'decision bad'}><h3>{result.recommendation.decision}</h3><p>{result.recommendation.message}</p><p>{result.recommendation.reason}</p><div className="mini-grid"><b>Profit<br/>{money(result.result.profit)}</b><b>Revenue<br/>{money(result.result.revenue)}</b><b>Confidence<br/>{result.confidence}/100</b><b>Guardrail<br/>{result.guardrail.status}</b></div><h4>Why?</h4>{result.why.map(x=><p key={x}>• {x}</p>)}</div>:<div className="empty"><BrainCircuit size={38}/><p>Run a scenario to see the decision.</p></div>}</section>}
function Results({result}){let d=result.monte_carlo.distribution.map((v,i)=>({p:i*10+5,value:v}));return <section className="panel"><div className="panel-head"><div><h2>Counterfactual outcome</h2><p>Baseline vs alternate future with uncertainty.</p></div><span className="pill">{result.monte_carlo.runs} Monte Carlo runs</span></div><div className="chart"><ResponsiveContainer width="100%" height={280}><BarChart data={[{name:'Current',profit:result.baseline.profit,revenue:result.baseline.revenue},{name:'Scenario',profit:result.result.profit,revenue:result.result.revenue}]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip formatter={v=>money(v)}/><Bar dataKey="revenue"/><Bar dataKey="profit"/></BarChart></ResponsiveContainer></div><div className="chart"><ResponsiveContainer width="100%" height={220}><AreaChart data={d}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="p"/><YAxis/><Tooltip formatter={v=>money(v)}/><Area type="monotone" dataKey="value"/></AreaChart></ResponsiveContainer></div><div className="mc"><b>Risk range:</b> P10 {money(result.monte_carlo.profit_p10)} · Expected {money(result.monte_carlo.expected_profit)} · P90 {money(result.monte_carlo.profit_p90)} · Positive probability {pct(result.monte_carlo.p_profit_positive)}<br/>Audit ID: <b>{result.audit_id}</b> · {result.guardrail.message}</div></section>}
function Optimizer({opt,optimize,busy}){return <section className="panel"><div className="panel-head"><div><h2>Profit-aware optimizer</h2><p>Search multiple counterfactual policies.</p></div><button onClick={optimize} disabled={busy}>{busy?'Optimizing…':'Optimize'}</button></div>{opt?<><div className="best">🏆 Best strategy: <b>{opt.best.discount_pct}% discount</b> → {money(opt.best.profit)} profit · {opt.tested} strategies</div><div className="chart"><ResponsiveContainer width="100%" height={240}><LineChart data={opt.scenarios}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="discount_pct" tickFormatter={v=>v+'%'}/><YAxis/><Tooltip formatter={v=>money(v)}/><Line type="monotone" dataKey="profit" strokeWidth={3}/></LineChart></ResponsiveContainer></div></>:<div className="empty">Find the best discount for your selected objective.</div>}</section>}
function Risk({radar}){return <section className="panel"><h2>Revenue Risk Radar</h2>{radar?.risks.map(x=><div className="risk" key={x.title}><b>{x.level}</b><div><strong>{x.title}</strong><p>{x.detail}</p></div></div>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);
